services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=flashsale_db'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=goyals'
    ports:
      - '5432:5432'
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
  kafka:
    image: 'confluentinc/cp-kafka:latest'
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAKFA_LISTENERS: 'PLAINTEXT://:9092,CONTROLLER://:9093'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@localhost:9093'
      KAKFA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
        - '9092:9092'
